### ISSUE TITLE
Snow Leopard text substitution support

### ISSUE THREAD

**Issue by mernen** [scrod/nv#120]
OS X Snow Leopard introduced system-wide text substitution support (normally accessed through the Edit->Substitutions menu, or a context menu), for things like smart quotes, smart dashes, and customizable predefined text replacement. It'd be really great if NV supported it.

**Comment by kimslawson** [comment]
@scrod, I enabled the above-mentioned option but it didn't work (i.e. typing strings featuring paired regular single ('') and double quotes ("") failed to produce smart quote pairs (‘’ and “”) in notes. I tried relaunching NV and checking and unchecking the smart quote and text substitution toggles in System Preferences > Keyboard > Text. Running NV 2.0 β5 (8) on 10.10.3.
