### ISSUE TITLE
Lost notes after folder change 

### ISSUE THREAD

**Issue by odavis** [scrod/nv#308]
My notes have disappeared after changing the default location of the notes folder to Dropbox. There doesn't  appear to be a Library/Application Support/Notational Data/ folder where I could find the original note file.

**Comment by samfader** [comment]
@scrod I am having the same issue, except I don't have a Library/Application Support/Notational Data/ folder anymore at all - and I've followed the above link to unhide the Library folder. Any other ideas? All my notes are blank now, unfortunately.
