### ISSUE TITLE
Note mysteriously deleting in front of me 

### ISSUE THREAD

**Issue by TheoA** [scrod/nv#321]
- I'm editing an existing note (it's been sync'd on other devices)
- I switch to another app, a few seconds later I notice that the note in the Notational Velocity window has disappeared leaving "No Note Selected"
- As soon as I see this I go back to NV and in the edit menu I see "Undo Delete 1 Notes"
- When I select undo, the note returns (The first time I thought I had accidentally hit delete)
- However this problem is now repeating every ~30-45 seconds
- When I check my iPhone SimpleNote app the note is gone too (i.e. NV sync'd the delete to Simple Note and it then disappeared on my iPhone), and when I undo of course, the note returns on my iPhone too.

Here is the OSX console log, I also made a screen recording available at http://ge.tt/6jdS5CS/v/0

---------------------------------------- Console Log ----------------------------------------
23/11/2012 10:50:14.364 Notational Velocity[37985]: load time: 2.6475, 
23/11/2012 10:50:14.377 Notational Velocity[37985]: finished: '/var/folders/1g/4zwqr0vd5_dc2hq4p4fwcq100000gp/T/NVProtectedEditingSpace'
23/11/2012 10:50:17.598 Notational Velocity[37985]: local: 0 added, 0 changed, 0 deleted, 0 to merge
23/11/2012 10:50:17.598 Notational Velocity[37985]: remote: 1 added, 0 changed, 0 deleted, 0 missing
23/11/2012 10:50:32.919 Notational Velocity[37985]: verified 547 notes in 0.033689 s
23/11/2012 11:06:41.987 Notational Velocity[38970]: load time: 6.38718, 
23/11/2012 11:06:42.002 Notational Velocity[38970]: finished: '/var/folders/1g/4zwqr0vd5_dc2hq4p4fwcq100000gp/T/NVProtectedEditingSpace'
23/11/2012 11:07:42.462 Notational Velocity[38970]: pushSyncServiceChanges: not pushing because a full sync index is in progress
23/11/2012 11:07:48.386 Notational Velocity[38970]: pushSyncServiceChanges: not pushing because a full sync index is in progress
23/11/2012 11:07:50.208 Notational Velocity[38970]: local: 0 added, 0 changed, 0 deleted, 0 to merge
23/11/2012 11:07:50.208 Notational Velocity[38970]: remote: 0 added, 0 changed, 0 deleted, 1 missing
23/11/2012 11:07:50.210 Notational Velocity[38970]: not writing note Git / {
} because it is not controlled by NoteController
23/11/2012 11:08:50.507 Notational Velocity[38970]: local: 0 added, 0 changed, 0 deleted, 0 to merge
23/11/2012 11:08:50.508 Notational Velocity[38970]: remote: 0 added, 0 changed, 0 deleted, 1 missing
23/11/2012 11:08:50.509 Notational Velocity[38970]: not writing note Git / {
} because it is not controlled by NoteController
23/11/2012 11:09:54.423 Notational Velocity[38970]: local: 0 added, 0 changed, 0 deleted, 0 to merge
23/11/2012 11:09:54.423 Notational Velocity[38970]: remote: 0 added, 0 changed, 0 deleted, 1 missing
23/11/2012 11:09:54.426 Notational Velocity[38970]: not writing note Git / {
} because it is not controlled by NoteController
23/11/2012 11:10:44.036 Notational Velocity[38970]: local: 1 added, 0 changed, 0 deleted, 0 to merge
23/11/2012 11:10:44.036 Notational Velocity[38970]: remote: 0 added, 0 changed, 0 deleted, 0 missing
23/11/2012 11:11:50.061 Notational Velocity[38970]: local: 0 added, 0 changed, 0 deleted, 0 to merge
23/11/2012 11:11:50.062 Notational Velocity[38970]: remote: 0 added, 0 changed, 0 deleted, 1 missing
23/11/2012 11:12:50.580 Notational Velocity[38970]: local: 0 added, 0 changed, 0 deleted, 0 to merge
23/11/2012 11:12:50.580 Notational Velocity[38970]: remote: 0 added, 0 changed, 0 deleted, 1 missing
23/11/2012 11:13:04.092 Notational Velocity[38970]: verified 547 notes in 0.034327 s
23/11/2012 11:13:09.662 Notational Velocity[39120]: load time: 3.77452, 
23/11/2012 11:13:09.678 Notational Velocity[39120]: finished: '/var/folders/1g/4zwqr0vd5_dc2hq4p4fwcq100000gp/T/NVProtectedEditingSpace'
23/11/2012 11:13:18.701 Notational Velocity[39120]: local: 0 added, 0 changed, 0 deleted, 0 to merge
23/11/2012 11:13:18.702 Notational Velocity[39120]: remote: 0 added, 0 changed, 0 deleted, 1 missing

**Comment by anagram** [comment]
this is happening to me today. I am turning off simplenote sync and hope that they stop trashing themselves
