### ISSUE TITLE
My notes disappeared after switching the "read notes from folder" folder

### ISSUE THREAD

**Issue by tonygives** [scrod/nv#348]
In seeking to relocate the location of my NV notes folder to dropbox as rtf files, I switched the "read notes from folder" to a new folder in dropbox, and switched the "store and read notes on disk as" option to rtf.

I realized this was a mistake subsequently and that I should have just moved the actual folder containing the notes, first, to relocate them.

Now I cannot find the original folder containing all my NV notes. It is not within LIbrary > Application Support > Notational Data , as I was hoping and a search for 'notational' reveals nothing.

Is there any way I can recover my notes? Thanks!

**Comment by tonygives** [comment]
found the hidden library folder within my user folder =) phew

**Comment by samfader** [comment]
@tonygives where did you find the folder? I'm having the same issue.
