### ISSUE TITLE
Password protection?

### ISSUE THREAD

**Issue by flaugher** [scrod/nv#350]
Are there any plans to add the ability for a user to password-protect the nvALT app itself so that the user must enter a password in order to start the app?  Thanks.

**Comment by scrod** [comment]
The app is named Notational Velocity, and it has always had "password protection". You can read in the wiki pages how your password is used to derive an encryption key:

https://github.com/scrod/nv/wiki/Database-Security

**Comment by flaugher** [comment]
Thank you.  I overlooked the Security tab in Preferences > Notes.
