### ISSUE TITLE
Download link on notational.net is no longer working

### ISSUE THREAD

**Issue by infomofo** [scrod/nv#371]
The download link at notational.net/NotationalVelocity.zip redirects to https://cloud.github.com/downloads/scrod/nv/Notational_Velocity_2_0b5.zip which is not available.

I get the following error:

```
This site can’t be reached

cloud.github.com’s server DNS address could not be found.
Try running Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by clw** [comment]
Yes, I managed to download it from http://github.com/downloads/scrod/nv/Notational_Velocity_2_0b5.zip instead.

**Comment by scrod** [comment]
Thanks for letting me know.
