### ISSUE TITLE
Building on M1 / Apple Silicon

### ISSUE THREAD

**Issue by n8henrie** [scrod/nv#392]
I just wanted to leave a note that I got NV building on arm64 / Apple Silicon, I've pushed a fork to <https://github.com/n8henrie/nv>.

I also got nvAlt running on arm64 and pushed a fork to <https://github.com/n8henrie/nvalt>; unfortunately GitHub didn't like me having two separate forks of the same project, so I "un"forked this one.

Just thought I'd leave a note in case anyone was interested in pursuing running natively on M1; it wasn't terribly difficulty, though I wasn't able to do a universal build due to having arm64-only dependencies (e.g. `/opt/homebrew/opt/openssl/lib/*`).

**Comment by jptechco** [comment]
For those interested, I’ve continued this work in a newer fork called Kinetic Notes, which is a modernized, actively maintained fork of Notational Velocity with native Apple Silicon support and universal builds. (Full disclosure: I’m the contributor behind KN.)

If you’re still interested in where NV has gone on modern macOS, you might take a look:  https://kineticnotes.org or https://github.com/jptechco/kn

**Comment by n8henrie** [comment]
Cool, thanks! I also updated and nixified [my nvalt fork](https://github.com/n8henrie/nvalt) a couple months ago, and it has been running well since then. It is janky and links to deprecated encryption libraries so it's nice that there is a proper modern alternative.
